# numpy-array

### 类型

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

arr = np.array([1, 2, 3, '4']) ##结构统一
print(arr)

arr = np.array([1, 2, 3, 4], dtype=np.float32)
print(arr)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
['1' '2' '3' '4']
[1. 2. 3. 4.]


### 属性

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape) ##几行几列
print(arr.size) ##元素个数
print(arr.ndim) ##几维

print(arr[1, 1]) ## 取几行几列的值
print(arr[1]) ## 取第几行的值
print(arr[:, 1]) ## 取第几列的值

(3, 3)
9
2
5
[4 5 6]
[2 5 8]


### 操作

In [13]:
arr = np.array([1, 2, 3, 4])
arr.fill(0)
print(arr)

[0 0 0 0]


In [18]:
arr2 = arr.copy() ##拷贝副本
arr2[1, 1] = 0
print(arr2)
print(arr)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr4 = np.arange(0, 100, 10)##0-100的等差数列
mask = arr4 > 40
print(mask)
print(arr4[mask])
print(arr4[np.where(arr4 > 40)])

[False False False False False  True  True  True  True  True]
[50 60 70 80 90]
[50 60 70 80 90]
