# numpy计算

### sum(求和)

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum())
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

21
[5 7 9]
[ 6 15]


### prod(求积)

In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.prod())
print(arr.prod(axis = 0))
print(arr.prod(axis = 1))

720
[ 4 10 18]
[  6 120]


### min max(最小值最大值)

In [20]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.min())
print(arr.min(axis = 0))
print(arr.min(axis = 1))

print(arr.argmin()) ##最小值的索引
print(arr.argmin(axis = 0))
print(arr.argmin(axis = 1))

1
[1 2 3]
[1 4]
0
[0 0 0]
[0 0]


### mean(平均数)

In [21]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.mean())
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

3.5
[2.5 3.5 4.5]
[2. 5.]


### std(标准差)

In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.std())
print(arr.std(axis = 0))
print(arr.std(axis = 1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


### var(方差)

In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.var())
print(arr.var(axis = 0))
print(arr.var(axis = 1))

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


### 矩阵乘法

In [3]:
x = np.array([[2, 3]])
y = np.array([[4], [5]])

print(np.dot(x, y))
print(np.dot(y, x))

[[23]]
[[ 8 12]
 [10 15]]


### 逻辑运算

In [4]:
x = np.array([1,2,3,4])
y = np.array([1,2,3,3])
print(x == y)
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))

[ True  True  True False]
[ True  True  True  True]
[ True  True  True  True]
[False False False False]
