# numpy-array 生成

### arange

In [2]:
import numpy as np
print(np.arange(10))
print(np.arange(2, 20, 2))

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


### linspace

In [5]:
print(np.linspace(0, 10, 20))

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


### logspace

In [6]:
## 默认以 10 为底的对数
print(np.logspace(0, 1, 5))

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


### 常用方法

In [3]:
print(np.zeros(3))
print(np.zeros((3, 3)))

print(np.ones((3, 3)))
print(np.ones((3, 3)) * 8)

a = np.array([[1, 2], [3, 4]])
print(np.zeros_like(a))
print(np.ones_like(a))

print(np.identity(5))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
