# 排序

### sort

In [1]:
import numpy as np
arr = np.array([[5, 1, 3], [6, 8, 2]])
print(np.sort(arr))
print(np.sort(arr, axis = 0))

[[1 3 5]
 [2 6 8]]
[[5 1 3]
 [6 8 2]]
[[5 1 2]
 [6 8 3]]


### argsort

In [2]:
import numpy as np
arr = np.array([[5, 1, 3], [6, 8, 2]])
print(np.argsort(arr))

[[1 2 0]
 [2 0 1]]


### searchsorted

In [1]:
## 定位 arr2 中元素位置
import numpy as np
arr = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 6])
print(np.searchsorted(arr, arr2))

[1 3]


### lexsort

In [10]:
## 先按照第三列升序排序，值相同的情况下按照第一列降序排列
import numpy as np
arr = np.array([[6, 0, 6], [1, 7, 0], [2, 3, 1], [2, 4, 0]])
index = np.lexsort([-1*arr[:, 0], arr[:, 2]])
print(arr[index])

[[2 4 0]
 [1 7 0]
 [2 3 1]
 [6 0 6]]
