# numpy形状操作

### shape

In [3]:
import numpy as np
arr = np.arange(10)
print(arr)
print(arr.shape)
arr.shape = 2,5
print(arr)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


### newaxis

In [9]:
arr = np.arange(10)
arr = arr[:, np.newaxis]
print(arr.shape)
print(arr)

arr = arr.squeeze() ## 压缩
print(arr)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]


### transpose

In [12]:
arr = np.arange(10)
arr.shape = 2,5
print(arr)

arr = arr.transpose()
print(arr)

arr = arr.T
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### concatenate

In [15]:
arr1 = np.array([[13, 23, 34], [2434, 343, 33]])
arr2 = np.array([[323, 434, 3434], [3422, 22, 22]])
arr3 = np.concatenate((arr1, arr2))
arr4 = np.concatenate((arr1, arr2), axis = 1)
print(arr3)
print(arr4)

[[  13   23   34]
 [2434  343   33]
 [ 323  434 3434]
 [3422   22   22]]
[[  13   23   34  323  434 3434]
 [2434  343   33 3422   22   22]]


### 拉平

In [18]:
### 方式1
arr = np.array([[13, 23, 34], [2434, 343, 33]])
arr1 = arr.flatten()
print(arr1)
### 方式2
arr = np.array([[13, 23, 34], [2434, 343, 33]])
arr2 = arr.ravel()
print(arr2)

[  13   23   34 2434  343   33]
[  13   23   34 2434  343   33]
