## numpy 随机模块

### 随机浮点数

In [4]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(3,4))

0.027589595158948654
[0.70619137 0.08524699 0.11155081 0.38776952 0.72079627]
[[0.39917699 0.37637231 0.51136948 0.10569582]
 [0.38864227 0.88752507 0.44748337 0.1056403 ]
 [0.81736477 0.7731074  0.22850299 0.22677815]]


### 随机整数

In [7]:
## [0,20) 之间的随机数
print(np.random.randint(20, size=(3,3)))
## 在 [0,10)之间找 3 个随机数
print(np.random.randint(0,10,3))

[[11 12  5]
 [14 10 16]
 [ 5 12 16]]
[9 1 9]


### 设置输出精度

In [13]:
np.set_printoptions(precision = 2)
np.random.rand(2,2)

array([[0.97, 0.8 ],
       [0.15, 0.81]])

### 洗牌

In [16]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[4 9 7 2 5 3 0 1 6 8]


### 随机种子

In [7]:
## 种子相同，每次随机出来的结果一致
np.random.seed(2)
print(np.random.randint(0, 10))

8
