## numpy 随机模块

### 随机浮点数

In [3]:
import numpy as np
print(np.random.rand())
print(np.random.rand(3,4))

0.47534023607834186
[[0.08080846 0.12797698 0.51378663 0.03776184]
 [0.22055419 0.10179457 0.95203915 0.63678254]
 [0.56993779 0.67454449 0.55945433 0.72512555]]


### 随机整数

In [7]:
## [0,20) 之间的随机数
print(np.random.randint(20, size=(3,3)))
## 在 [0,10)之间找 3 个随机数
print(np.random.randint(0,10,3))

[[11 12  5]
 [14 10 16]
 [ 5 12 16]]
[9 1 9]


### 设置输出精度

In [13]:
np.set_printoptions(precision = 2)
np.random.rand(2,2)

array([[0.97, 0.8 ],
       [0.15, 0.81]])

### 洗牌

In [16]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[4 9 7 2 5 3 0 1 6 8]


### 随机种子

In [24]:
## 种子相同，每次随机出来的结果一致
np.random.seed(2)
print(np.random.randint(0, 10))

8
