## 文件操作

In [12]:
%%writefile ./data/numpy.txt
1 2 3 4 5
6 7 8 9 10

Overwriting ./data/numpy.txt


In [13]:
%%writefile ./data/numpy1.txt
a b c d e
1 2 3 4 5
6 7 8 9 10

Writing ./data/numpy1.txt


### txt 文件读取

In [20]:
import numpy as np
## 分隔符
data = np.loadtxt('./data/numpy.txt', delimiter=' ')
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [21]:
## 去掉几行
data = np.loadtxt('./data/numpy1.txt', skiprows=1)
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [22]:
## 使用哪几列
data = np.loadtxt('./data/numpy.txt', usecols=(0,1))
print(data)

[[1. 2.]
 [6. 7.]]


### txt 文件写入

In [24]:
data = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('./data/numpy2.txt', data, fmt="%d")

### array 文件读写

In [25]:
## 单个 array
data = np.array([[1,2,3],[4,5,6]])
np.save('./data/a.npy', data)
out = np.load('./data/a.npy')
print(out)

[[1 2 3]
 [4 5 6]]


In [37]:
## 多个 array
data1 = np.array([1,2,3])
data2 = np.array([4,5,6])
np.savez('./data/b.npz', a = data1, b = data2)
out = np.load('./data/b.npz')
print(out['a'])
print(out['b'])

[1 2 3]
[4 5 6]
